### ISSUE TITLE
java.lang.AssertionError: Parameter P surely belongs to class ...

### ISSUE THREAD

**Issue by baratynskiy** [Baratynskiy/kotlin-netbeans#103]
Occurs sometimes during project analyzing.

**Comment by baratynskiy** [comment]
```
java.lang.AssertionError: Parameter T surely belongs to class com.intellij.extapi.psi.StubBasedPsiElementBase, so it must be resolved
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassDescriptor$declaredParameters$1.invoke(LazyJavaClassDescriptor.kt:123)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassDescriptor$declaredParameters$1.invoke(LazyJavaClassDescriptor.kt:48)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:321)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:362)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassDescriptor.getDeclaredTypeParameters(LazyJavaClassDescriptor.kt:127)
	at org.jetbrains.kotlin.descriptors.TypeParameterUtilsKt.computeConstructorTypeParameters(typeParameterUtils.kt:27)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassDescriptor$LazyJavaClassTypeConstructor$parameters$1.invoke(LazyJavaClassDescriptor.kt:137)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassDescriptor$LazyJavaClassTypeConstructor$parameters$1.invoke(LazyJavaClassDescriptor.kt:135)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:321)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:362)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassDescriptor$LazyJavaClassTypeConstructor.getParameters(LazyJavaClassDescriptor.kt:140)
	at org.jetbrains.kotlin.load.java.lazy.types.LazyJavaTypeResolver$LazyJavaClassifierType.computeArguments(LazyJavaTypeResolver.kt:194)
	at org.jetbrains.kotlin.types.AbstractLazyType$arguments$1.invoke(AbstractLazyType.kt:32)
	at org.jetbrains.kotlin.types.AbstractLazyType$arguments$1.invoke(AbstractLazyType.kt:25)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:321)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:362)
	at org.jetbrains.kotlin.types.AbstractLazyType.getArguments(AbstractLazyType.kt:33)
	at org.jetbrains.kotlin.types.AbstractLazyType.getSubstitution(AbstractLazyType.kt:37)
	at org.jetbrains.kotlin.types.AbstractLazyType.computeMemberScope(AbstractLazyType.kt:48)
	at org.jetbrains.kotlin.types.AbstractLazyType$memberScope$1.invoke(AbstractLazyType.kt:41)
	at org.jetbrains.kotlin.types.AbstractLazyType$memberScope$1.invoke(AbstractLazyType.kt:25)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:321)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:362)
	at org.jetbrains.kotlin.types.AbstractLazyType.getMemberScope(AbstractLazyType.kt:42)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.getPropertiesFromSupertypes(LazyJavaClassMemberScope.kt:470)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.computeNonDeclaredProperties(LazyJavaClassMemberScope.kt:368)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$properties$1.invoke(LazyJavaScope.kt:234)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$properties$1.invoke(LazyJavaScope.kt:51)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:394)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:458)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope.getContributedVariables(LazyJavaScope.kt:290)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.getContributedVariables(LazyJavaClassMemberScope.kt:674)
	at org.jetbrains.kotlin.resolve.scopes.SubstitutingScope.getContributedVariables(SubstitutingScope.kt:68)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.getPropertiesFromSupertypes(LazyJavaClassMemberScope.kt:470)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.computeNonDeclaredProperties(LazyJavaClassMemberScope.kt:368)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$properties$1.invoke(LazyJavaScope.kt:234)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$properties$1.invoke(LazyJavaScope.kt:51)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:394)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:458)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope.getContributedVariables(LazyJavaScope.kt:290)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.getContributedVariables(LazyJavaClassMemberScope.kt:674)
	at org.jetbrains.kotlin.resolve.scopes.SubstitutingScope.getContributedVariables(SubstitutingScope.kt:68)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.getPropertiesFromSupertypes(LazyJavaClassMemberScope.kt:470)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.computeNonDeclaredProperties(LazyJavaClassMemberScope.kt:368)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$properties$1.invoke(LazyJavaScope.kt:234)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$properties$1.invoke(LazyJavaScope.kt:51)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:394)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:458)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope.getContributedVariables(LazyJavaScope.kt:290)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.getContributedVariables(LazyJavaClassMemberScope.kt:674)
	at org.jetbrains.kotlin.resolve.scopes.SubstitutingScope.getContributedVariables(SubstitutingScope.kt:68)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.getPropertiesFromSupertypes(LazyJavaClassMemberScope.kt:470)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.computeNonDeclaredProperties(LazyJavaClassMemberScope.kt:368)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$properties$1.invoke(LazyJavaScope.kt:234)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$properties$1.invoke(LazyJavaScope.kt:51)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:394)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:458)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope.getContributedVariables(LazyJavaScope.kt:290)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.getContributedVariables(LazyJavaClassMemberScope.kt:674)
	at org.jetbrains.kotlin.resolve.scopes.SubstitutingScope.getContributedVariables(SubstitutingScope.kt:68)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.getPropertiesFromSupertypes(LazyJavaClassMemberScope.kt:470)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.computeNonDeclaredProperties(LazyJavaClassMemberScope.kt:368)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$properties$1.invoke(LazyJavaScope.kt:234)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$properties$1.invoke(LazyJavaScope.kt:51)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:394)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:458)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope.getContributedVariables(LazyJavaScope.kt:290)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.getContributedVariables(LazyJavaClassMemberScope.kt:674)
	at org.jetbrains.kotlin.resolve.scopes.SubstitutingScope.getContributedVariables(SubstitutingScope.kt:68)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.getPropertiesFromSupertypes(LazyJavaClassMemberScope.kt:470)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.computeNonDeclaredProperties(LazyJavaClassMemberScope.kt:368)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$properties$1.invoke(LazyJavaScope.kt:234)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope$properties$1.invoke(LazyJavaScope.kt:51)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:394)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:458)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaScope.getContributedVariables(LazyJavaScope.kt:290)
	at org.jetbrains.kotlin.load.java.lazy.descriptors.LazyJavaClassMemberScope.getContributedVariables(LazyJavaClassMemberScope.kt:674)
	at org.jetbrains.kotlin.resolve.calls.tower.ReceiverScopeTowerLevel$getVariables$1.invoke(TowerLevels.kt:127)
	at org.jetbrains.kotlin.resolve.calls.tower.ReceiverScopeTowerLevel$getVariables$1.invoke(TowerLevels.kt:82)
	at org.jetbrains.kotlin.resolve.calls.tower.ReceiverScopeTowerLevel.collectMembers(TowerLevels.kt:91)
	at org.jetbrains.kotlin.resolve.calls.tower.ReceiverScopeTowerLevel.getVariables(TowerLevels.kt:127)
	at org.jetbrains.kotlin.resolve.calls.tower.ScopeTowerProcessorsKt$createVariableProcessor$1.invoke(ScopeTowerProcessors.kt:143)
	at org.jetbrains.kotlin.resolve.calls.tower.ScopeTowerProcessorsKt$createVariableProcessor$1.invoke(ScopeTowerProcessors.kt)
	at org.jetbrains.kotlin.resolve.calls.tower.ExplicitReceiverScopeTowerProcessor.resolveAsMember(ScopeTowerProcessors.kt:67)
	at org.jetbrains.kotlin.resolve.calls.tower.ExplicitReceiverScopeTowerProcessor.simpleProcess(ScopeTowerProcessors.kt:60)
	at org.jetbrains.kotlin.resolve.calls.tower.AbstractSimpleScopeTowerProcessor.process(ScopeTowerProcessors.kt:50)
	at org.jetbrains.kotlin.resolve.calls.tower.CompositeScopeTowerProcessor.process(ScopeTowerProcessors.kt:40)
	at org.jetbrains.kotlin.resolve.calls.tower.TowerResolver.processTowerData(TowerResolver.kt:194)
	at org.jetbrains.kotlin.resolve.calls.tower.TowerResolver.access$processTowerData(TowerResolver.kt:76)
	at org.jetbrains.kotlin.resolve.calls.tower.TowerResolver$run$1.invoke(TowerResolver.kt:111)
	at org.jetbrains.kotlin.resolve.calls.tower.TowerResolver.run(TowerResolver.kt:125)
	at org.jetbrains.kotlin.resolve.calls.tower.TowerResolver.runResolve(TowerResolver.kt:81)
	at org.jetbrains.kotlin.resolve.calls.tower.NewResolutionOldInference.runResolution(NewResolutionOldInference.kt:148)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.doResolveCall(CallResolver.java:599)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.doResolveCallOrGetCachedResults(CallResolver.java:516)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.access$100(CallResolver.java:65)
	at org.jetbrains.kotlin.resolve.calls.CallResolver$1.invoke(CallResolver.java:186)
	at org.jetbrains.kotlin.resolve.calls.CallResolver$1.invoke(CallResolver.java:180)
	at org.jetbrains.kotlin.util.PerformanceCounter.time(PerformanceCounter.kt:92)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.computeTasksAndResolveCall(CallResolver.java:180)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.computeTasksAndResolveCall(CallResolver.java:170)
	at org.jetbrains.kotlin.resolve.calls.CallResolver.resolveSimpleProperty(CallResolver.java:124)
	at org.jetbrains.kotlin.resolve.calls.CallExpressionResolver.getVariableType(CallExpressionResolver.kt:104)
	at org.jetbrains.kotlin.resolve.calls.CallExpressionResolver.getSimpleNameExpressionTypeInfo(CallExpressionResolver.kt:136)
	at org.jetbrains.kotlin.resolve.calls.CallExpressionResolver.getUnsafeSelectorTypeInfo(CallExpressionResolver.kt:305)
	at org.jetbrains.kotlin.resolve.calls.CallExpressionResolver.getSafeOrUnsafeSelectorTypeInfo(CallExpressionResolver.kt:333)
	at org.jetbrains.kotlin.resolve.calls.CallExpressionResolver.getQualifiedExpressionTypeInfo(CallExpressionResolver.kt:422)
	at org.jetbrains.kotlin.types.expressions.BasicExpressionTypingVisitor.visitQualifiedExpression(BasicExpressionTypingVisitor.java:686)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.visitQualifiedExpression(ExpressionTypingVisitorDispatcher.java:384)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher$ForDeclarations.visitQualifiedExpression(ExpressionTypingVisitorDispatcher.java:55)
	at org.jetbrains.kotlin.psi.KtVisitor.visitDotQualifiedExpression(KtVisitor.java:290)
	at org.jetbrains.kotlin.psi.KtDotQualifiedExpression.accept(KtDotQualifiedExpression.kt:31)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher$1.invoke(ExpressionTypingVisitorDispatcher.java:182)
Caused: org.jetbrains.kotlin.util.KotlinFrontEndException: Exception while analyzing expression at (51,34) in C:/.../kotlin-netbeans/src/main/java/org/jetbrains/kotlin/structurescanner/KotlinFunctionStructureItem.kt:
function.name

	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.logOrThrowException(ExpressionTypingVisitorDispatcher.java:254)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.access$200(ExpressionTypingVisitorDispatcher.java:48)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher$1.invoke(ExpressionTypingVisitorDispatcher.java:224)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher$1.invoke(ExpressionTypingVisitorDispatcher.java:172)
	at org.jetbrains.kotlin.util.PerformanceCounter.time(PerformanceCounter.kt:92)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.getTypeInfo(ExpressionTypingVisitorDispatcher.java:172)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.getTypeInfo(ExpressionTypingVisitorDispatcher.java:143)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingVisitorDispatcher.getTypeInfo(ExpressionTypingVisitorDispatcher.java:155)
	at org.jetbrains.kotlin.types.expressions.ExpressionTypingServices.getBodyExpressionType(ExpressionTypingServices.java:202)
	at org.jetbrains.kotlin.resolve.DescriptorResolver$3.invoke(DescriptorResolver.java:969)
	at org.jetbrains.kotlin.resolve.DescriptorResolver$3.invoke(DescriptorResolver.java:965)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedLazyValue.invoke(LockBasedStorageManager.java:321)
	at org.jetbrains.kotlin.storage.LockBasedStorageManager$LockBasedNotNullLazyValue.invoke(LockBasedStorageManager.java:362)
	at org.jetbrains.kotlin.types.DeferredType.getDelegate(DeferredType.java:90)
	at org.jetbrains.kotlin.types.DelegatingType.getCapability(DelegatingType.java:73)
	at org.jetbrains.kotlin.types.TypeCapabilitiesKt.sameTypeConstructors(TypeCapabilities.kt:84)
	at org.jetbrains.kotlin.types.checker.TypeCheckingProcedure.isSubtypeOf(TypeCheckingProcedure.java:187)
	at org.jetbrains.kotlin.types.checker.KotlinTypeChecker.isSubtypeOf(KotlinTypeChecker.java:62)
	at org.jetbrains.kotlin.resolve.OverrideResolver.isReturnTypeOkForOverride(OverrideResolver.java:734)
	at org.jetbrains.kotlin.resolve.OverrideResolver.checkOverridesForMember(OverrideResolver.java:708)
	at org.jetbrains.kotlin.resolve.OverrideResolver.checkOverridesForMemberMarkedOverride(OverrideResolver.java:669)
	at org.jetbrains.kotlin.resolve.OverrideResolver.checkOverrideForMember(OverrideResolver.java:578)
	at org.jetbrains.kotlin.resolve.OverrideResolver.checkOverridesInAClass(OverrideResolver.java:106)
	at org.jetbrains.kotlin.resolve.OverrideResolver.checkOverrides(OverrideResolver.java:99)
	at org.jetbrains.kotlin.resolve.OverrideResolver.check(OverrideResolver.java:58)
	at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzer.analyzeDeclarations(LazyTopDownAnalyzer.kt:187)
	at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzerForTopLevel.analyzeDeclarations(LazyTopDownAnalyzerForTopLevel.java:74)
	at org.jetbrains.kotlin.resolve.LazyTopDownAnalyzerForTopLevel.analyzeFiles(LazyTopDownAnalyzerForTopLevel.java:66)
	at org.jetbrains.kotlin.resolve.NetBeansAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(NetBeansAnalyzerFacadeForJVM.kt:69)
	at org.jetbrains.kotlin.diagnostics.netbeans.parser.KotlinAnalysisProjectCache.getResult(KotlinAnalysisProjectCache.kt:45)
	at org.jetbrains.kotlin.diagnostics.netbeans.parser.KotlinAnalysisProjectCache.getAnalysisResult(KotlinAnalysisProjectCache.kt:36)
	at org.jetbrains.kotlin.diagnostics.netbeans.parser.KotlinParser$Companion.getAnalysisResult(KotlinParser.kt:58)
	at org.jetbrains.kotlin.diagnostics.netbeans.parser.KotlinParser.getAnalysisResult(KotlinParser.kt)
	at org.jetbrains.kotlin.projectsextensions.KotlinProjectHelper$1$1.run(KotlinProjectHelper.java:88)
Caused: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Failed to generate function getSortText
Cause: Exception while analyzing expression at (51,34) in C:/.../kotlin-netbeans/src/main/java/org/jetbrains/kotlin/structurescanner/KotlinFunctionStructureItem.kt:
function.name

File being compiled and position: (51,5) in C:/.../kotlin-netbeans/src/main/java/org/jetbrains/kotlin/structurescanner/KotlinFunctionStructureItem.kt
PsiElement: override fun getSortText() = function.name
The root cause was thrown at: ExpressionTypingVisitorDispatcher.java:254
	at org.jetbrains.kotlin.codegen.MemberCodegen.genFunctionOrProperty(MemberCodegen.java:190)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateDeclaration(ClassBodyCodegen.java:124)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateBody(ClassBodyCodegen.java:74)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:118)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:232)
	at org.jetbrains.kotlin.codegen.PackageCodegen.generateClassOrObject(PackageCodegen.java:145)
	at org.jetbrains.kotlin.codegen.PackageCodegen.generateFile(PackageCodegen.java:98)
	at org.jetbrains.kotlin.codegen.PackageCodegen.generate(PackageCodegen.java:61)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.generatePackage(KotlinCodegenFacade.java:99)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:77)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:44)
	at org.jetbrains.kotlin.filesystem.lightclasses.KotlinLightClassGeneration.buildLightClasses(KotlinLightClassGeneration.kt:68)
	at org.jetbrains.kotlin.filesystem.lightclasses.KotlinLightClassGeneration.getByteCode(KotlinLightClassGeneration.kt:105)
	at org.jetbrains.kotlin.filesystem.KotlinVirtualSourceProvider.getByteCode(KotlinVirtualSourceProvider.java:83)
	at org.jetbrains.kotlin.filesystem.KotlinVirtualSourceProvider.translate(KotlinVirtualSourceProvider.java:53)
	at org.netbeans.modules.java.source.usages.VirtualSourceProviderQuery.translate(VirtualSourceProviderQuery.java:155)
	at org.netbeans.modules.java.source.indexing.JavaCustomIndexer.translateVirtualSources(JavaCustomIndexer.java:398)
	at org.netbeans.modules.java.source.indexing.JavaCustomIndexer.index(JavaCustomIndexer.java:211)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor$2.run(Indexable.java:161)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runIndexer(RepositoryUpdater.java:298)
	at org.netbeans.modules.parsing.spi.indexing.Indexable$MyAccessor.index(Indexable.java:159)
[catch] at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doIndex(RepositoryUpdater.java:2773)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.access$800(RepositoryUpdater.java:2177)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work$1.run(RepositoryUpdater.java:2659)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work$1.run(RepositoryUpdater.java:2657)
	at org.netbeans.modules.parsing.impl.indexing.errors.TaskCache.refreshTransaction(TaskCache.java:565)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.index(RepositoryUpdater.java:2657)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work$3.call(RepositoryUpdater.java:3315)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work$3.call(RepositoryUpdater.java:3281)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$4.run(RepositoryUpdater.java:2150)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2146)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.runInContext(RepositoryUpdater.java:2127)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater.access$1500(RepositoryUpdater.java:159)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.scanFiles(RepositoryUpdater.java:3281)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$FileListWork.getDone(RepositoryUpdater.java:3800)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Work.doTheWork(RepositoryUpdater.java:3435)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task._run(RepositoryUpdater.java:6198)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.access$4300(RepositoryUpdater.java:5849)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2$1.run(RepositoryUpdater.java:6114)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:304)
	at org.netbeans.modules.parsing.impl.RunWhenScanFinishedSupport.performScan(RunWhenScanFinishedSupport.java:106)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6110)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task$2.call(RepositoryUpdater.java:6106)
	at org.netbeans.modules.masterfs.filebasedfs.utils.FileChangedManager.priorityIO(FileChangedManager.java:176)
	at org.netbeans.modules.masterfs.providers.ProvidedExtensions.priorityIO(ProvidedExtensions.java:360)
	at org.netbeans.modules.parsing.nb.DataObjectEnvFactory.runPriorityIO(DataObjectEnvFactory.java:141)
	at org.netbeans.modules.parsing.impl.Utilities.runPriorityIO(Utilities.java:88)
	at org.netbeans.modules.parsing.impl.indexing.RepositoryUpdater$Task.run(RepositoryUpdater.java:6106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```
