### ISSUE TITLE
java.lang.IllegalArgumentException in NB 8.2 for 0.1.1-beta

### ISSUE THREAD

**Issue by rumatoest** [Baratynskiy/kotlin-netbeans#107]
While opening file from http://bit.ly/kodewars it fails to show me any code - just empty window.

Plus exception appears in logs

```
java.lang.IllegalArgumentException: Already a /home/******/.netbeans/8.2/nbproject/project.xml@85c9bb9f:4c92648a
	at org.netbeans.spi.project.support.ant.ProjectGenerator$1.run(ProjectGenerator.java:128)
	at org.netbeans.spi.project.support.ant.ProjectGenerator$1.run(ProjectGenerator.java:123)
	at org.netbeans.modules.openide.util.DefaultMutexImplementation.writeAccess(DefaultMutexImplementation.java:250)
	at org.openide.util.Mutex.writeAccess(Mutex.java:299)
	at org.netbeans.spi.project.support.ant.ProjectGenerator.createProject0(ProjectGenerator.java:123)
	at org.netbeans.spi.project.support.ant.ProjectGenerator.createProject(ProjectGenerator.java:104)
	at org.jetbrains.kotlin.utils.KotlinMockProject.createHelper(KotlinMockProject.kt:43)
	at org.jetbrains.kotlin.utils.KotlinMockProject.getMockProject(KotlinMockProject.kt:49)
	at org.jetbrains.kotlin.builder.KotlinPsiManager.getParsedKtFileForSyntaxHighlighting(KotlinPsiManager.kt:132)
	at org.jetbrains.kotlin.highlighter.KotlinTokenScanner.<init>(KotlinTokenScanner.kt:34)
	at org.jetbrains.kotlin.highlighter.KotlinTokenScanner.<init>(KotlinTokenScanner.kt:26)
	at org.jetbrains.kotlin.highlighter.netbeans.KotlinLexerProxy$kotlinTokenScanner$2.invoke(KotlinLexerProxy.kt:28)
	at org.jetbrains.kotlin.highlighter.netbeans.KotlinLexerProxy$kotlinTokenScanner$2.invoke(KotlinLexerProxy.kt:26)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
	at org.jetbrains.kotlin.highlighter.netbeans.KotlinLexerProxy.getKotlinTokenScanner(KotlinLexerProxy.kt)
	at org.jetbrains.kotlin.highlighter.netbeans.KotlinLexerProxy.nextToken(KotlinLexerProxy.kt:32)
	at org.netbeans.lib.lexer.LexerInputOperation.nextToken(LexerInputOperation.java:215)
	at org.netbeans.lib.lexer.inc.IncTokenList.tokenOrEmbeddingImpl(IncTokenList.java:195)
	at org.netbeans.lib.lexer.inc.IncTokenList.tokenOrEmbedding(IncTokenList.java:190)
	at org.netbeans.lib.lexer.LexerUtilsConstants.tokenIndexLazyTokenCreation(LexerUtilsConstants.java:317)
	at org.netbeans.lib.lexer.inc.IncTokenList.tokenIndex(IncTokenList.java:172)
	at org.netbeans.api.lexer.TokenSequence.move(TokenSequence.java:680)
	at org.netbeans.modules.editor.lib2.highlighting.SyntaxHighlighting$HSImpl.<init>(SyntaxHighlighting.java:381)
	at org.netbeans.modules.editor.lib2.highlighting.SyntaxHighlighting.getHighlights(SyntaxHighlighting.java:139)
	at org.netbeans.modules.editor.lib2.highlighting.DirectMergeContainer$HlSequence.<init>(DirectMergeContainer.java:232)
	at org.netbeans.modules.editor.lib2.highlighting.DirectMergeContainer.getHighlights(DirectMergeContainer.java:119)
	at org.netbeans.modules.editor.lib2.highlighting.HighlightsReader.<init>(HighlightsReader.java:65)
	at org.netbeans.modules.editor.lib2.view.HighlightsViewFactory.restart(HighlightsViewFactory.java:190)
	at org.netbeans.modules.editor.lib2.view.ViewBuilder$FactoryState.init(ViewBuilder.java:1324)
	at org.netbeans.modules.editor.lib2.view.ViewBuilder.createViews(ViewBuilder.java:724)
	at org.netbeans.modules.editor.lib2.view.ViewBuilder.createReplaceRepaintViews(ViewBuilder.java:685)
	at org.netbeans.modules.editor.lib2.view.ViewUpdates.reinitAllViews(ViewUpdates.java:214)
	at org.netbeans.modules.editor.lib2.view.DocumentViewOp.checkViewsInited(DocumentViewOp.java:642)
	at org.netbeans.modules.editor.lib2.view.DocumentView.getPreferredSpan(DocumentView.java:251)
	at javax.swing.plaf.basic.BasicTextUI$RootView.getPreferredSpan(BasicTextUI.java:1353)
	at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:919)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1333)
	at org.netbeans.modules.editor.NbEditorUI$LayeredEditorPane.getPreferredSize(NbEditorUI.java:478)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validate(Container.java:1630)
	at org.netbeans.core.windows.view.ui.DesktopImpl$LayeredLayout.layoutContainer(DesktopImpl.java:554)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validate(Container.java:1630)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by baratynskiy** [comment]
Gradle projects are not supported yet.

**Comment by rumatoest** [comment]
I do not think that you should support gradle directly. Netbeans has separate plugin for gradle and it is compatible with any language plugin.
