### ISSUE TITLE
Exception while saving a file (?)

### ISSUE THREAD

**Issue by mglukhikh** [Baratynskiy/kotlin-netbeans#69]
I just took lesson6/task2/Chess.kt from KotlinAsFirst project and changed `data class Square` to:

```
data class Square(val column: Int, val row: Int) {
    fun inside(): Boolean = TODO()

    fun notation(): String = if (!inside()) "" else "abcdefgh"[row - 1] + "$column"
}
```

Stack trace

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'descriptor' of org/jetbrains/kotlin/codegen/context/CodegenContext.intoPackagePart must not be null
    at org.jetbrains.kotlin.codegen.context.CodegenContext.intoPackagePart(CodegenContext.java)
    at org.jetbrains.kotlin.codegen.PackageCodegen.generateFile(PackageCodegen.java:87)
    at org.jetbrains.kotlin.codegen.PackageCodegen.generate(PackageCodegen.java:61)
    at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.generatePackage(KotlinCodegenFacade.java:99)
    at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:77)
    at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:44)
    at org.jetbrains.kotlin.filesystem.lightclasses.KotlinLightClassGeneration.buildLightClasses(KotlinLightClassGeneration.java:108)
    at org.jetbrains.kotlin.filesystem.lightclasses.KotlinLightClassGeneration.generate(KotlinLightClassGeneration.java:214)
    at org.jetbrains.kotlin.indexer.KotlinIndexer.generateLightClass(KotlinIndexer.java:67)
    at org.jetbrains.kotlin.indexer.KotlinIndexer.access$000(KotlinIndexer.java:38)
    at org.jetbrains.kotlin.indexer.KotlinIndexer$2.run(KotlinIndexer.java:59)
[catch] at java.lang.Thread.run(Thread.java:745)
```

**Comment by mglukhikh** [comment]
I'm not 100% sure it's a bug of NetBeans plugin itself

**Comment by Chris2011** [comment]
So it is a bug of the underliying kotlin compiler?

**Comment by baratynskiy** [comment]
No, it was a bug of NetBeans plugin.

**Comment by Chris2011** [comment]
Ok.
