### ISSUE TITLE
java.lang.AssertionError: package fragment is null for JetFile: 	at org.jetbrains.kotlin.codegen.PackageCodegen.getOnlyPackageFragment(PackageCodegen.java:125)

### ISSUE THREAD

**Issue by markiewb** [Baratynskiy/kotlin-netbeans#71]
![2016-09-15 20h49_00](https://cloud.githubusercontent.com/assets/1857095/18563246/3e1213ac-7b87-11e6-881c-495911372682.gif)

```
java.lang.AssertionError: package fragment is null for JetFile:
    at org.jetbrains.kotlin.codegen.PackageCodegen.getOnlyPackageFragment(PackageCodegen.java:125)
    at org.jetbrains.kotlin.codegen.PackageCodegen.<init>(PackageCodegen.java:53)
    at org.jetbrains.kotlin.codegen.ClassFileFactory.forPackage(ClassFileFactory.java:197)
    at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.generatePackage(KotlinCodegenFacade.java:98)
    at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:77)
    at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:44)
    at org.jetbrains.kotlin.filesystem.lightclasses.KotlinLightClassGeneration.buildLightClasses(KotlinLightClassGeneration.java:108)
    at org.jetbrains.kotlin.filesystem.lightclasses.KotlinLightClassGeneration.generate(KotlinLightClassGeneration.java:214)
    at org.jetbrains.kotlin.indexer.KotlinIndexer.generateLightClass(KotlinIndexer.java:67)
    at org.jetbrains.kotlin.indexer.KotlinIndexer.access$000(KotlinIndexer.java:38)
    at org.jetbrains.kotlin.indexer.KotlinIndexer$2.run(KotlinIndexer.java:59)
[catch] at java.lang.Thread.run(Thread.java:745)
```

**Comment by mglukhikh** [comment]
Thank you for verbose description!
