### ISSUE TITLE
Does not work -> Null pointer exception on latest version in netbeans respository for nb 8.2

### ISSUE THREAD

**Issue by rumatoest** [Baratynskiy/kotlin-netbeans#95]
Unable to open any kotlin file. Shows me empty window without any content.

NullPointerException at org.jetbrains.kotlin.utils.KotlinMockProject.getMockProject

The same happens when I'm trying to create kotlin file

java.lang.NullPointerException
	at org.jetbrains.kotlin.utils.ProjectUtils.getKotlinProjectForFileObject(ProjectUtils.java:196)
	at org.jetbrains.kotlin.builder.KotlinPsiManager.parseText(KotlinPsiManager.java:95)
	at org.jetbrains.kotlin.builder.KotlinPsiManager.parseFile(KotlinPsiManager.java:82)
	at org.jetbrains.kotlin.builder.KotlinPsiManager.parseTextForDiagnostic(KotlinPsiManager.java:122)
	at org.jetbrains.kotlin.utils.ProjectUtils.getKtFile(ProjectUtils.java:161)
	at org.jetbrains.kotlin.reformatting.FormatUtilsKt.format(formatUtils.kt:34)
	at org.jetbrains.kotlin.reformatting.KotlinReformatTask.reformat(KotlinReformatTask.kt:32)
	at org.netbeans.modules.editor.indent.TaskHandler$MimeItem.runTask(TaskHandler.java:575)
	at org.netbeans.modules.editor.indent.TaskHandler.runTasks(TaskHandler.java:334)
	at org.netbeans.modules.editor.indent.IndentImpl.reformat(IndentImpl.java:365)
	at org.netbeans.modules.editor.indent.api.Reformat.reformat(Reformat.java:154)
	at org.netbeans.editor.ActionFactory.reformat(ActionFactory.java:1913)
	at org.netbeans.editor.BaseDocument$Accessor.ActionFactory_reformat(BaseDocument.java:2598)
	at org.netbeans.modules.editor.EditorModule$6.run(EditorModule.java:586)
	at org.netbeans.editor.GuardedDocument.runAtomicAsUser(GuardedDocument.java:356)
	at org.openide.text.NbDocument.runAtomicAsUser(NbDocument.java:462)
	at org.netbeans.modules.editor.EditorModule.reformat(EditorModule.java:580)
	at org.netbeans.modules.editor.EditorModule.access$100(EditorModule.java:105)
	at org.netbeans.modules.editor.EditorModule$4.operationCreateFromTemplate(EditorModule.java:260)
	at org.openide.loaders.DataLoaderPool.fireOperationEvent(DataLoaderPool.java:240)
	at org.openide.loaders.DataObject.fireOperationEvent(DataObject.java:1011)
	at org.openide.loaders.DataObject.createFromTemplate(DataObject.java:984)
	at org.jetbrains.kotlin.file.wizard.classwizard.KtClassWizardIterator.instantiate(KtClassWizardIterator.java:106)
	at org.openide.loaders.TemplateWizard$InstantiatingIteratorBridge.instantiate(TemplateWizard.java:1053)
	at org.openide.loaders.TemplateWizard.handleInstantiate(TemplateWizard.java:605)
	at org.openide.loaders.TemplateWizard.instantiateNewObjects(TemplateWizard.java:439)
	at org.openide.loaders.TemplateWizardIterImpl.instantiate(TemplateWizardIterImpl.java:248)
	at org.openide.loaders.TemplateWizardIteratorWrapper.instantiate(TemplateWizardIteratorWrapper.java:160)
	at org.openide.WizardDescriptor.callInstantiateOpen(WizardDescriptor.java:1629)
	at org.openide.WizardDescriptor.callInstantiate(WizardDescriptor.java:1570)
	at org.openide.WizardDescriptor.access$2300(WizardDescriptor.java:92)
[catch] at org.openide.WizardDescriptor$Listener$2$1.run(WizardDescriptor.java:2257)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

**Comment by baratynskiy** [comment]
Probably related to #93

**Comment by rumatoest** [comment]
Just forgot to mention that I used gradle project. Url http://bit.ly/kodewars
